# Generated by Django 5.2.8 on 2025-11-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gallery_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=100)),
                ('area_of_interest', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True)),
                ('is_processed', models.BooleanField(default=False, help_text='Mark as processed/contacted')),
                ('is_approved', models.BooleanField(default=False, help_text='Mark as approved member')),
                ('notes', models.TextField(blank=True, help_text='Admin notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Join Us Submission',
                'verbose_name_plural': 'Join Us Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
