# Generated by Django 5.2.8 on 2025-11-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_joinsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Newsletter title (e.g., 'IYN Monthly - January 2025')", max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(help_text='Brief description of this newsletter edition')),
                ('cover_image', models.ImageField(blank=True, help_text='Cover image/thumbnail', upload_to='newsletters/covers/')),
                ('file', models.FileField(help_text='Newsletter PDF or document', upload_to='newsletters/files/')),
                ('issue_number', models.CharField(blank=True, help_text="e.g., 'Vol 1, Issue 3'", max_length=50)),
                ('publication_date', models.DateField(help_text='Date this newsletter was published')),
                ('is_published', models.BooleanField(default=True, help_text='Make this newsletter publicly available')),
                ('download_count', models.IntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
                'ordering': ['-publication_date'],
            },
        ),
    ]
